// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx7CBS_xdIQyV0PL00Kh2vXM70zNIK1_Q',
    appId: '1:214080802316:web:fc499ecdd6108d5609e829',
    messagingSenderId: '214080802316',
    projectId: 'flutter-delivery-api',
    authDomain: 'flutter-delivery-api.firebaseapp.com',
    databaseURL: 'https://flutter-delivery-api-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-delivery-api.firebasestorage.app',
    measurementId: 'G-6KBNM02BV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVTMXpnVYePke3rCam9_5e9g5ZWG9xtIY',
    appId: '1:214080802316:android:9e2f03c2864cb5cb09e829',
    messagingSenderId: '214080802316',
    projectId: 'flutter-delivery-api',
    databaseURL: 'https://flutter-delivery-api-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-delivery-api.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9jzFqO5k_4yEElkOcIpj3XLFjMJmwOI4',
    appId: '1:214080802316:ios:044f3ab029ab2dbf09e829',
    messagingSenderId: '214080802316',
    projectId: 'flutter-delivery-api',
    databaseURL: 'https://flutter-delivery-api-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-delivery-api.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9jzFqO5k_4yEElkOcIpj3XLFjMJmwOI4',
    appId: '1:214080802316:ios:044f3ab029ab2dbf09e829',
    messagingSenderId: '214080802316',
    projectId: 'flutter-delivery-api',
    databaseURL: 'https://flutter-delivery-api-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-delivery-api.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx7CBS_xdIQyV0PL00Kh2vXM70zNIK1_Q',
    appId: '1:214080802316:web:0eb1b9d7f7478f4d09e829',
    messagingSenderId: '214080802316',
    projectId: 'flutter-delivery-api',
    authDomain: 'flutter-delivery-api.firebaseapp.com',
    databaseURL: 'https://flutter-delivery-api-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-delivery-api.firebasestorage.app',
    measurementId: 'G-QHEDDW6KFJ',
  );
}